---
title: "process results of network generated"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: united
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# General settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)

```

## Packages

```{r, message=F, warning =F}
library(tidyverse)
library(ggplot2); theme_set(cowplot::theme_cowplot(font_size = 15))
library(reshape2)
library(ggrepel)
library(knitr)
library(Biostrings)
library(RColorBrewer)
library(org.Hs.eg.db)
library(OmnipathR)
library(here)

mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by
```

```{r}
options(ggplot2.discrete.colour= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
options(ggplot2.discrete.fill= c("orange3", "darkslateblue", "darkred", "darkgreen", "darkgrey", "darkviolet"))
```

## Load data 
Network was generated by Mira Burtscher
```{r}
load("data/processed_data/230427_kinase_enrichment_result.RData")
```


test
## Load network

```{r}
combined_edges_df <- bind_rows(
  "early" = read_tsv(here("Code/corneto/results/230616_fourthtry/output/combinededges_df.tsv")),
  "late" = read_tsv(here("Code/corneto/results/230616_fourthtry/output/combinededges_df_2.tsv")),
  .id = "network"
) %>% 
  filter(!grepl("inflow", edge)) %>% 
  separate(edge, into = c("source", "sign", "target"), remove = F, sep = "--") %>% 
  select(-value)

combined_nodes_df <- bind_rows(
  "early" = read_tsv(here("Code/corneto/results/230616_fourthtry/output/combinednodes_df.tsv")),
  "late" = read_tsv(here("Code/corneto/results/230616_fourthtry/output/combinednodes_df_2.tsv")),
  .id = "network"
) 
```

## annotations

```{r}
enzyme_anno <- bind_rows("TF" = decoupleR::get_dorothea(organism='human', levels=c('A', 'B', 'C')),
                  "Kinase" = res_kinase_enrichment$KSN,
                  .id = "type") %>% 
  distinct(type, source)


enzymes <- bind_rows("early"= read_csv(here("Code/corneto/results/230616_fourthtry/enzymes_df.csv")),
                     "late" = read_csv(here("Code/corneto/results/230616_fourthtry/enzymes_df_late.csv")),
                     .id = "network") %>% 
  left_join(enzyme_anno) %>% bind_rows(
    bind_rows(
  "early" = read_csv(here("Code/corneto/results/230616_fourthtry/secretome_df.csv")),
  "late" = read_csv(here("Code/corneto/results/230616_fourthtry/secretome_df_late.csv")),
  .id = "network"
) %>% 
  mutate(type = "secreted", source= id)) %>% 
  dplyr::select(-id)

node_df <- combined_nodes_df%>% 
  left_join(enzymes, by = c("node"= "source", "network")) %>% 
  mutate(type = ifelse(is.na(type), "PKN", type))

```

```{r}
edges <- combined_edges_df %>% 
  filter(network == "late") %>% 
  select(from = source, to = target)

nodes <- node_df %>% 
  filter(network == "late" & !(grepl("_", node))) %>% 
  mutate(id = node) %>% 
  distinct(id, type) %>% 
  mutate(group = type)
```


```{r}
library(visNetwork)
set.seed(1)
p <- visNetwork(nodes, edges) %>%
  # standard options
  visGroups(groupname = "Kinase", color = "darkcyan") %>%
  visGroups(groupname = "TF", color = "mediumvioletred") %>%
  visGroups(groupname = "PKN", color = "gray") %>%
  visGroups(groupname = "secreted", color = "mediumseagreen") %>%
  visEdges(arrows = "to", color = "dimgrey", width = 2) %>%
  visNodes(font = "30px arial black bold") %>%
  visLegend() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visNetwork::visIgraphLayout(layout = "layout_with_fr")
p
```

```{r}
edges <- combined_edges_df %>% 
  select(from = source, to = target) %>% 
  filter(from == "COL1A1") %>% 
  distinct(from, to)

nodes <- node_df %>% 
  filter(node %in% c(edges$from, edges$to) & !(grepl("_", node))) %>% 
  mutate(id = node) %>% 
  distinct(id, type) %>% 
  mutate(group = type) %>% 
  distinct(id)
  filter(!(id == "ADGRG1" & type == "PKN"))
```


```{r}
library(visNetwork)
set.seed(1)
p <- visNetwork(nodes, edges) %>%
  # standard options
  visGroups(groupname = "Kinase", color = "darkcyan") %>%
  visGroups(groupname = "TF", color = "mediumvioletred") %>%
  visGroups(groupname = "PKN", color = "gray") %>%
  visGroups(groupname = "secreted", color = "mediumseagreen") %>%
  visEdges(arrows = "to", color = "dimgrey", width = 2) %>%
  visNodes(font = "30px arial black bold") %>%
  visLegend() %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
  visNetwork::visIgraphLayout(layout = "layout_with_fr")
p
```


## save
```{r, eval = F}

combined_edges_df %>% 
  write_csv(file = here("Code/corneto/230616_fourthtry/output/cytoscape_network.csv"))

node_df %>% 
  write_csv(file = here("Code/corneto/230616_fourthtry/output/cytoscape_nodes.csv"))

```

## enrichment

```{r}
library(decoupleR)
msigdf_decoupler <- msigdbr::msigdbr(species = "Homo sapiens", category = "C2") %>%
  transmute(source = str_replace(gs_name, "HALLMARK_", ""), mor = 1, target = gene_symbol) %>%
  distinct() %>% 
  filter(grepl("REACTOME", source))


enrichment <- node_df %>% 
  mutate(value = ifelse(is.na(score), value, score))  %>% 
  select(-score, -type) %>% 
  ungroup() %>% 
  distinct(network, node, value)%>% 
  group_by(network) %>% 
  nest(data = c(node, value))%>% 
  mutate(ER = map(data, function(df) { 
    x = df %>% mutate(dummy = "dummy") %>%  acast(node ~ dummy, value.var = "value", fun.aggregate = mean)
    decoupleR::run_wmean(mat = x, network = msigdf_decoupler)
  }
)) %>% 
  select(-data) %>% 
  unnest(cols = c(ER))


enrichment %>% 
  filter(p_value <= 0.05 & statistic == "norm_wmean") %>% 
  ggplot(aes(x = -log10(p_value), y = source, size = abs(score), colour = factor(sign(score)))) +
  geom_point() +
  scale_colour_manual(values = c("red", "dodgerblue")) +
  facet_wrap(~network) +
  theme_bw()
```

```{r}
load(here("Code/corneto/input/diff_results_20230322.RData"))
library(ReactomePA)
GSE_RPA <- function(geneList, universe) {
  geneList <- mapIds(org.Hs.eg.db, geneList, "ENTREZID", "SYMBOL")
  universe <- mapIds(org.Hs.eg.db, universe,'ENTREZID','SYMBOL')
  pathway_enrichment <- enrichPathway(
    gene = geneList,
    organism = "human",
    pvalueCutoff = 1,
    pAdjustMethod = "BH",
    qvalueCutoff = 1,
    universe = universe,
    minGSSize = 5,
    maxGSSize = 500,
    readable = TRUE
  )
}

universe <- unique(diff_results$feature_id)
universe <- gsub("_.*$", "", universe)
universe <- unique(universe)

pathwayenrichment_RPA <-node_df %>%
  group_by(network) %>%
  mutate(enrichment = list(as.data.frame(GSE_RPA(
    geneList = node,
    universe = universe
  ))))

pathway_enrichment_unnest <- pathwayenrichment_RPA %>%
  distinct(network, enrichment) %>%
  unnest()

interesting <- pathway_enrichment_unnest %>% 
  filter(qvalue <= 0.01 & Count > 15)

pathway_enrichment_unnest %>% 
  filter(Description %in% interesting$Description) %>% 
  ggplot(aes(x = -log10(qvalue), y = reorder(Description, qvalue), size = Count, colour = network)) +
  geom_vline(xintercept = -log10(0.01), linetype = 3) +
  geom_line(aes(group = Description), colour = "black", size =0.5) +
  geom_point() +
  scale_colour_manual(values = c("red", "dodgerblue")) +
  theme_bw()

interesting <- c(
  "Signaling by Receptor Tyrosine Kinases",
  "Signaling by TGFB family members",
"Signaling by Interleukins",
"Extracellular matrix organization",
"ECM proteoglycans",
"Degradation of the extracellular matrix")

pathway_enrichment_unnest %>% 
  filter(Description %in% interesting) %>% 
  mutate(Description = factor(Description, levels = interesting)) %>% 
  ggplot(aes(x = -log10(qvalue), y = Description, colour = network)) +
  geom_vline(xintercept = -log10(0.01), linetype = 3) +
  geom_line(aes(group = Description), colour = "black", size =0.5) +
  geom_point(size = 3) +
  scale_colour_manual(values = c("red", "dodgerblue")) +
  theme_bw(base_size = 14)
```


Zoom in into e.g. CCN2
```{r}
int <- pathway_enrichment_unnest %>% 
  filter(Description ==  "Signaling by TGFB family members") %>% 
  select(geneID) %>% 
  mutate(genes = str_split(geneID, pattern = "/")) %>% 
  select(-geneID) %>% 
  unnest(cols = genes)


edges <- combined_edges_df %>% 
  select(from = source, to = target)

int <- edges %>% 
  filter(from == "E2F1")

int <- c("BGN", "COL5A1", "COL7A1", "IGFB7", "MMP2", "SERPINE2","TGFBI")

int <- "CCN2"

tilted <-  theme(axis.text.x = element_text(angle = 45, hjust =1, vjust = 1))
diff_results %>% 
  filter(feature_id %in% int) %>% 
     mutate(
     time = factor(time, levels = c("0h", "0.08h", "1h", "12h", "24h", "48h", "72h", "96h")),
     group = paste0(modality, feature_id)) %>% 
  ggplot(aes(x = time, y = logFC, colour = modality, group =group, shape = modality )) +
  geom_hline(yintercept = c(log2(1.5), 0, log2(1/1.5))) +
  geom_point() +
  #geom_line() +
  geom_smooth(se = F) +
  facet_wrap(~feature_id, ncol = 1) +
  cowplot::panel_border() +
  tilted
```


## cluster network

Cluster network and annotate nodes with cluster information
### late network 
```{r}
library(igraph)
graph <- combined_edges_df %>%
  ungroup() %>% 
  filter(network == "late") %>% 
  select(from=source, to=target, sign) %>%
  mutate(sign= as.numeric(str_extract(sign, "-\\d|\\d"))) %>% 
  distinct(from, to) %>%
  igraph::graph_from_data_frame()

graph_UD <- as.undirected(graph, mode = "collapse")
cfg <- igraph::cluster_fluid_communities(graph_UD, no.of.communities = 8)

n_clusters <- length(unique(cfg$membership))
n_clusters

clusters <- data.frame(node = cfg$names, cluster = cfg$membership)

node_df_clusters <- node_df %>%
  ungroup() %>% 
  select(network,  node, type) %>% 
  filter(network == "late") %>% 
  inner_join(clusters, by = "node") %>%
  mutate(cluster = as.factor(cluster)) %>% 
  distinct(node, cluster, type)
```


```{r}
library(ggraph)
pal <- c(
  "1" = "#EE7733",
  "2" = "#0077BB",
  "3" = "#33BBEE",
  "4" = "#EE3377",
  "5" = "#CC3311",
  "6" = "#009988",
  "7" = "#BBBBBB",
  "8" = "#71b448",
  "9" = "darkblue",
  "10" = "goldenrod",
  "11" = "mediumvioletred",
  "12" = "darkred"
)

target <- clusters$node
node_df_clusters <- node_df_clusters[match(target, node_df_clusters$node), ] 

set.seed(4)
p <- ggraph(graph, layout = "fr") +
  geom_edge_link(
    colour = "grey50",
    end_cap = circle(3, "mm"),
    start_cap = circle(3, "mm")
  ) +
  geom_node_point(aes(colour = node_df_clusters$cluster),size = 6) +
  geom_node_text(aes(label = node_df_clusters$node), size = 1.5) +
  scale_colour_manual(values = pal) +
 # scale_shape_manual(values = c(15:20, 25)) +
  theme_graph() +
  theme(legend.position = "right")
p
```

### early network

```{r}
library(igraph)
graph <- combined_edges_df %>%
  ungroup() %>% 
  filter(network == "early") %>% 
  select(from=source, to=target, sign) %>%
  mutate(sign= as.numeric(str_extract(sign, "-\\d|\\d"))) %>% 
  distinct(from, to) %>%
  igraph::graph_from_data_frame()

graph_UD <- as.undirected(graph, mode = "collapse")
cfg <- igraph::cluster_fluid_communities(graph_UD, no.of.communities = 8)

n_clusters <- length(unique(cfg$membership))
n_clusters

clusters <- data.frame(node = cfg$names, cluster = cfg$membership)

node_df_clusters <- node_df %>%
  ungroup() %>% 
  select(network,  node, type) %>% 
  filter(network == "early") %>% 
  inner_join(clusters, by = "node") %>%
  mutate(cluster = as.factor(cluster)) %>% 
  distinct(node, cluster, type)
```


```{r}
library(ggraph)
pal <- c(
  "1" = "#EE7733",
  "2" = "#0077BB",
  "3" = "#33BBEE",
  "4" = "#EE3377",
  "5" = "#CC3311",
  "6" = "#009988",
  "7" = "#BBBBBB",
  "8" = "#71b448",
  "9" = "darkblue",
  "10" = "goldenrod",
  "11" = "mediumvioletred",
  "12" = "darkred"
)

target <- clusters$node
node_df_clusters <- node_df_clusters[match(target, node_df_clusters$node), ] 
#mutate(shape = factor(node_df_clusters$cluster))

set.seed(4)
p <- ggraph(graph, layout = "fr") +
  geom_edge_link(
    colour = "grey50",
    end_cap = circle(3, "mm"),
    start_cap = circle(3, "mm")
  ) +
  geom_node_point(aes(colour = node_df_clusters$cluster),size = 6) +
  geom_node_text(aes(label = node_df_clusters$node), size = 1.5) +
  scale_colour_manual(values = pal) +
 # scale_shape_manual(values = c(15:20, 25)) +
  theme_graph() +
  theme(legend.position = "right")
p
```



### cluster level enrichment

```{r}
# PKN as universe
universe <- unique(diff_results$feature_id)
universe <- gsub("_.*$", "", universe)
universe <- unique(universe)

pathwayenrichment_cluster <- node_df_clusters %>%
  group_by(cluster) %>%
  mutate(enrichment = list(as.data.frame(GSE_RPA(
    geneList = node,
    universe = universe
  ))))

pathway_enrichment_unnest_cluster<- pathwayenrichment_cluster %>%
  distinct(cluster, enrichment) %>%
  unnest()
```

```{r}
pathway_enrichment_top3cluster <- pathway_enrichment_unnest_cluster %>%
  filter(Count > 2) %>%
  ungroup() %>%
  mutate(corr_p_value = -log10(p.adjust)) %>%
  group_by(cluster) %>%
  dplyr::arrange(cluster, desc(corr_p_value), desc(Count)) %>%
  slice_head(n = 3)

pathway_enrichment_unnest_cluster %>% 
  filter(Description %in% pathway_enrichment_top3cluster$Description) %>% 
  ggplot(aes(x = -log10(qvalue), y = reorder(Description, qvalue), size = Count, colour = cluster)) +
  geom_vline(xintercept = -log10(0.01), linetype = 3) +
  geom_line(aes(group = Description), colour = "black", size =0.5) +
  geom_point() +
  scale_colour_manual(values = pal) +
  theme_bw()

```
